config/routes.rb
Rails.application.routes.draw do
  resources(:favorites)
  resource(:schedule)
  resources(:shopping_carts)
  resources(:ticket_orders)
  resources(:tickets)
  resources(:gigs)
  resources(:concerts)
  resources(:bands)
  resources(:venues)
  devise_for(:users)
  root(to: "schedules#show")
end

app/models/concert.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
# == Schema Information
#
# Table name: concerts
#
#  id          :bigint           not null, primary key
#  access      :enum
#  description :text
#  genre_tags  :text
#  ilk         :enum
#  name        :string
#  start_time  :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  venue_id    :bigint           not null
#

# class GoodnessValidator < ActiveModel::Validator
#   def validate(record)
#     # if record.first_name == "Evil"
#       record.errors.add :base, "This person is evil"
#     # end
#   end
# end

class Concert < ApplicationRecord
  belongs_to :venue
  has_many(
    :gigs,
    -> { order(order: :asc) },
    dependent: :destroy,
    inverse_of: :concert
  )

  has_many :bands, through: :gigs
  has_many :tickets, dependent: :destroy

  # validates_with GoodnessValidator
  validates :name, presence: true

  enum ilk: {concert: "concert", meet_n_greet: "meet_n_greet", battle: "battle"}
  enum access: {general: "general", members: "members", vips: "vips"}

  def start_day
    start_time.to_date
  end

  def duration_minutes
    gigs.map(&:duration_minutes).sum
  end

  def genre_parameters
    genre_tags.split(",").map(&:parameterize).join(",")
  end

  def unsold_ticket_count
    tickets.unsold.count
  end

  def sold_out?
    unsold_ticket_count.zero?
  end

  def sell_out!
    tickets.update_all(status: :purchased, user: User.hoarder)
  end

  def find_ticket_at(row:, number:)
    tickets.find { |ticket| ticket.row == row && ticket.number == number }
  end

  def self.random_purchase_all!(min = 10, max = 30)
    Concert.find_each { |concert| concert.random_purchase!(min, max) }
  end

  def random_purchase!(min = 10, max = 30)
    purchase = rand(min..max)

    purchase.times do
      tickets.unsold.sample.update(status: :purchased, user: User.hoarder)
    end
  end
end

app/controllers/concerts_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/nrclient for more book information.
#---
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
    if params[:inline]
      render(@concert)
    end
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html do
          redirect_to(@concert, notice: "Concert was successfully created.")
        end

        format.json { render(:show, status: :created, location: @concert) }
      else
        format.html { render(:new) }

        format.json do
          render(json: @concert.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html do
          # redirect_to(@concert, notice: "Concert was successfully updated.")
          render(@concert)
        end

        format.json { render(:show, status: :ok, location: @concert) }
      else
        format.html { render(:edit) }

        format.json do
          render(json: @concert.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy

    respond_to do |format|
      format.html do
        redirect_to(concerts_url, notice: "Concert was successfully destroyed.")
      end

      format.json { head(:no_content) }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_concert
    @concert = Concert.includes(:tickets).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  private def concert_params
    params.require(:concert).permit(
      :name,
      :description,
      :start_time,
      :venue_id,
      :genre_tags,
      :ilk,
      :access
    )
  end
end

app/views/concerts/_concert.html.haml
= turbo_frame_tag(dom_id(concert)) do
  %hr/
  %article.py-4
    .grid.gap-4.grid-cols-5
      .col-span-1.text-xl
        = concert.start_time.by_example("3:04 PM")
      .col-span-3
        .name
          .text-lg.font-bold
            = link_to(concert.name, concert, data: {"turbo-frame": "_top"})
        .bands
          = concert.bands.map(&:name).join(", ")
        .genres
          = concert.genre_tags.split(",").to_sentence
        .text-gray-500.font-bold
          = concert.venue.name
      .col-span-1
        - if concert.sold_out?
          Sold out
        - else
          = pluralize(concert.unsold_ticket_count, "Tickets")
          Remaining
        %br/
        %br/
        .flex.space-x-4
          - if current_user
            - if current_user
              = link_to(                                                                                 |
                  edit_concert_path(concert),                                                            |
                  class: SimpleForm.button_class, |
                  title: "Edit"                                                                          |
                ) do                                                                                     |
                %svg.w-6.h-6{:fill => "none", :stroke => "currentColor", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
                  %path{:d => "M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
            - if current_user.favorite(concert)
              = render("shared/favorite_button",                           |
                  path: favorite_path(id: current_user.favorite(concert)), |
                  method: "delete",                                        |
                  enabled: current_user.favorite(concert),                 |
                  title: "Add to Favorite"                                 |
                )                                                          |
            - else
              = render("shared/favorite_button",                |
                  path: favorites_path(concert_id: concert.id), |
                  method: "post",                               |
                  enabled: current_user.favorite(concert),      |
                  title: "Make Favorite"                        |
                )                                               |

app/views/concerts/_form.html.haml
= turbo_frame_tag(dom_id(concert)) do
  = simple_form_for(@concert) do |f|
    - if f.object.errors.present?
      .text-red-500.border-red-800.font-bold.border-2.p-2.mb-2
        = f.error_notification
        = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
    %article.my-4
      .grid.gap-4.grid-cols-5
        .col-span-1.text-xl
          = f.input :start_time, label: false
        .col-span-3
          .name
            .text-lg.font-bold
              = f.input :name, label: false
              = f.input :description, label: false
          .bands
            = concert.bands.map(&:name).join(", ")
          .genres
            = f.input :genre_tags, label: false
          .text-gray-500.font-bold
            = f.association :venue, label: false
        .col-span-1.text-xl.my-10
          = f.input :ilk, collection: Concert.ilks, label: false
          = f.input :access, collection: Concert.accesses, label: false
          = f.button :submit, class: "border-solid border-2 border-gray-800 rounded p-1"
          = link_to "Cancel", concert_path(@concert, inline: true), class: "#{SimpleForm.button_class} border-solid border-2 border-gray-800 rounded p-1"

app/views/concerts/edit.html.haml
%h1 Editing Concert
= render "form", concert: @concert
= link_to "Show", @concert
|
= link_to "Back", concerts_path

app/views/concerts/index.html.haml
%p#notice= notice
%h1 Concerts
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Start time
      %th Venue
      %th Genre tags
      %th Ilk
      %th Access
      %th{:colspan => "3"}
  %tbody
    - @concerts.each do |concert|
      %tr
        %td= concert.name
        %td= concert.description
        %td= concert.start_time
        %td= concert.venue_id
        %td= concert.genre_tags
        %td= concert.ilk
        %td= concert.access
        %td= link_to "Show", concert
        %td= link_to "Edit", edit_concert_path(concert)
        %td= link_to "Destroy", concert, method: :delete, data: {confirm: "Are you sure?"}
%br/
= link_to "New Concert", new_concert_path

app/views/concerts/new.html.haml
%h1 New Concert
= render "form", concert: @concert
= link_to "Back", concerts_path

app/views/concerts/show.html.haml
%h1.text-4xl.font-bold.w-auto.text-center= @concert.name
%h2.text-2xl.font-semibold Ticket Info
%h3.text-xl= @concert.ilk
%h3.text-xl= @concert.access
%h3.text-xl
  Start Date:  
  \#{@concert.start_time.by_example("Jan 02, 2006")}
%h3.text-xl
  Venue: #{@concert.venue.name}
%h3.text-xl Schedule:
- running_time = @concert.start_time
%table.table.border.border-black{:class => "w-4/5"}
  %thead
    %tr
      %th Time
      %th Band
      %th Genres
  %tbody
    - @concert.gigs.each do |gig|
      %tr
        %td= running_time.by_example("03:04 PM")
        %td= gig.band.name
        %td= gig.band.genre_tags.split(",").join(", ")
        - running_time += (gig.duration_minutes * 60)
%h2.text-2xl.font-semibold.mt-12 Tickets
.concert
  .header
    %span Current Tickets Purchased:  
    %span 0
  .header
    %span Current Tickets Cost:  
    %span $0.00
  .px-5.py-4.m-2.my-4.w-40.text-center.text-white.transition-colors.duration-150.bg-gray-800.rounded-lg.focus:shadow-outline.hover:bg-black
    Clear Tickets
  %div
    %span.header How many tickets would you like?
    %span.select
      %select
        = @concert.venue.seats_per_row.times do |seat|
          %option= seat + 1
  %table.table
    %tbody
      - @concert.venue.rows.times do |row|
        %tr
          - @concert.venue.seats_per_row.times do |seat|
            - ticket = @concert.find_ticket_at(row: row + 1, number: seat + 1)
            %td
              - if ticket.present?
                = link_to(ticket_path(ticket.id), method: :patch) do
                  %div{:class => "#{ticket.color_for(current_user)} p-4 m-2 border-black border-4 button hover:bg-blue-300 text-lg"}
                    = seat + 1
              - else
                %h1
                  error row #{row}, seat #{seat}
.actions
  = link_to("Edit", edit_concert_path(@concert))
  |
  \#{link_to("Back", concerts_path)}